#logging:
#  level:
#    guru:
#      springframework:
#        controllers: INFO
#    org:
#      hibernate: INFO
#      springframework:
#        web: INFO
#  pattern:
#    console: '%d %-5level %logger : %msg%n'
#    file: '%d %-5level [%thread] %logger : %msg%n'
server:
  port: 8085

spring:
  application:
    name: salonyours-employee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/yem_db_2020?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: yem_admin_2020
    password: baMZ8ctJaiVX.tu

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


#
#eureka:
#  client:
#    healthcheck:
#      enabled: true